var searchData=
[
  ['scalarbinaryoptraits_0',['ScalarBinaryOpTraits',['../../structEigen_1_1ScalarBinaryOpTraits.html',1,'Eigen']]],
  ['select_1',['Select',['../../classEigen_1_1Select.html',1,'Eigen']]],
  ['selfadjointeigensolver_2',['SelfAdjointEigenSolver',['../../classEigen_1_1SelfAdjointEigenSolver.html',1,'Eigen']]],
  ['selfadjointview_3',['SelfAdjointView',['../../classEigen_1_1SelfAdjointView.html',1,'Eigen']]],
  ['serializer_4',['Serializer',['../../classEigen_1_1Serializer.html',1,'Eigen']]],
  ['sgroup_5',['SGroup',['../classEigen_1_1SGroup.html',1,'Eigen']]],
  ['simplicialcholesky_6',['SimplicialCholesky',['../../classEigen_1_1SimplicialCholesky.html',1,'Eigen']]],
  ['simplicialcholeskybase_7',['SimplicialCholeskyBase',['../../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialcholesky_3c_20matrixtype_5f_2c_20uplo_5f_2c_20ordering_5f_20_3e_20_3e_8',['SimplicialCholeskyBase&lt; SimplicialCholesky&lt; MatrixType_, UpLo_, Ordering_ &gt; &gt;',['../../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialldlt_3c_20matrixtype_5f_2c_20uplo_5f_2c_20ordering_5f_20_3e_20_3e_9',['SimplicialCholeskyBase&lt; SimplicialLDLT&lt; MatrixType_, UpLo_, Ordering_ &gt; &gt;',['../../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialllt_3c_20matrixtype_5f_2c_20uplo_5f_2c_20ordering_5f_20_3e_20_3e_10',['SimplicialCholeskyBase&lt; SimplicialLLT&lt; MatrixType_, UpLo_, Ordering_ &gt; &gt;',['../../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialldlt_11',['SimplicialLDLT',['../../classEigen_1_1SimplicialLDLT.html',1,'Eigen']]],
  ['simplicialllt_12',['SimplicialLLT',['../../classEigen_1_1SimplicialLLT.html',1,'Eigen']]],
  ['skewsymmetricbase_13',['SkewSymmetricBase',['../../classEigen_1_1SkewSymmetricBase.html',1,'Eigen']]],
  ['skewsymmetricbase_3c_20skewsymmetricmatrix3_3c_20scalar_5f_20_3e_20_3e_14',['SkewSymmetricBase&lt; SkewSymmetricMatrix3&lt; Scalar_ &gt; &gt;',['../../classEigen_1_1SkewSymmetricBase.html',1,'Eigen']]],
  ['skewsymmetricbase_3c_20skewsymmetricwrapper_3c_20skewsymmetricvectortype_5f_20_3e_20_3e_15',['SkewSymmetricBase&lt; SkewSymmetricWrapper&lt; SkewSymmetricVectorType_ &gt; &gt;',['../../classEigen_1_1SkewSymmetricBase.html',1,'Eigen']]],
  ['skewsymmetricmatrix3_16',['SkewSymmetricMatrix3',['../../classEigen_1_1SkewSymmetricMatrix3.html',1,'Eigen']]],
  ['skewsymmetricwrapper_17',['SkewSymmetricWrapper',['../../classEigen_1_1SkewSymmetricWrapper.html',1,'Eigen']]],
  ['skylineinplacelu_18',['SkylineInplaceLU',['../classEigen_1_1SkylineInplaceLU.html',1,'Eigen']]],
  ['skylinematrix_19',['SkylineMatrix',['../classEigen_1_1SkylineMatrix.html',1,'Eigen']]],
  ['skylinematrixbase_20',['SkylineMatrixBase',['../classEigen_1_1SkylineMatrixBase.html',1,'Eigen']]],
  ['skylinematrixbase_3c_20skylinematrix_3c_20scalar_5f_2c_20options_5f_20_3e_20_3e_21',['SkylineMatrixBase&lt; SkylineMatrix&lt; Scalar_, Options_ &gt; &gt;',['../classEigen_1_1SkylineMatrixBase.html',1,'Eigen']]],
  ['skylinestorage_22',['SkylineStorage',['../classEigen_1_1SkylineStorage.html',1,'Eigen']]],
  ['solve_23',['Solve',['../../classEigen_1_1Solve.html',1,'Eigen']]],
  ['solverbase_24',['SolverBase',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20colpivhouseholderqr_3c_20matrixtype_5f_2c_20permutationindex_5f_20_3e_20_3e_25',['SolverBase&lt; ColPivHouseholderQR&lt; MatrixType_, PermutationIndex_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20completeorthogonaldecomposition_3c_20matrixtype_5f_2c_20permutationindex_5f_20_3e_20_3e_26',['SolverBase&lt; CompleteOrthogonalDecomposition&lt; MatrixType_, PermutationIndex_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20fullpivhouseholderqr_3c_20matrixtype_5f_2c_20permutationindex_5f_20_3e_20_3e_27',['SolverBase&lt; FullPivHouseholderQR&lt; MatrixType_, PermutationIndex_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20fullpivlu_3c_20matrixtype_5f_2c_20permutationindex_5f_20_3e_20_3e_28',['SolverBase&lt; FullPivLU&lt; MatrixType_, PermutationIndex_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20householderqr_3c_20matrixtype_5f_20_3e_20_3e_29',['SolverBase&lt; HouseholderQR&lt; MatrixType_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20ldlt_3c_20matrixtype_5f_2c_20uplo_5f_20_3e_20_3e_30',['SolverBase&lt; LDLT&lt; MatrixType_, UpLo_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20llt_3c_20matrixtype_5f_2c_20uplo_5f_20_3e_20_3e_31',['SolverBase&lt; LLT&lt; MatrixType_, UpLo_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20partialpivlu_3c_20matrixtype_5f_2c_20permutationindex_5f_20_3e_20_3e_32',['SolverBase&lt; PartialPivLU&lt; MatrixType_, PermutationIndex_ &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20svdbase_3c_20derived_20_3e_20_3e_33',['SolverBase&lt; SVDBase&lt; Derived &gt; &gt;',['../../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverstorage_34',['SolverStorage',['../../structEigen_1_1SolverStorage.html',1,'Eigen']]],
  ['solvewithguess_35',['SolveWithGuess',['../../classEigen_1_1SolveWithGuess.html',1,'Eigen']]],
  ['sparse_36',['Sparse',['../../structEigen_1_1Sparse.html',1,'Eigen']]],
  ['sparsecompressedbase_37',['SparseCompressedBase',['../../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20scalar_5f_2c_20options_5f_2c_20storageindex_5f_20_3e_20_3e_38',['SparseCompressedBase&lt; SparseMatrix&lt; Scalar_, Options_, StorageIndex_ &gt; &gt;',['../../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsevector_3c_20scalar_5f_2c_20options_5f_2c_20storageindex_5f_20_3e_20_3e_39',['SparseCompressedBase&lt; SparseVector&lt; Scalar_, Options_, StorageIndex_ &gt; &gt;',['../../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparseinverse_40',['SparseInverse',['../classEigen_1_1SparseInverse.html',1,'Eigen']]],
  ['sparselu_41',['SparseLU',['../../classEigen_1_1SparseLU.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20readonlyaccessors_20_3e_42',['SparseMapBase&lt; Derived, ReadOnlyAccessors &gt;',['../../classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20writeaccessors_20_3e_43',['SparseMapBase&lt; Derived, WriteAccessors &gt;',['../../classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4.html',1,'Eigen']]],
  ['sparsematrix_44',['SparseMatrix',['../../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_20_3e_45',['SparseMatrix&lt; Scalar, ColMajor &gt;',['../../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_20_3e_46',['SparseMatrix&lt; Scalar, RowMajor &gt;',['../../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrixbase_47',['SparseMatrixBase',['../../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e_48',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['../../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrix_3c_20scalar_5f_2c_20_5fblockatcompiletime_2c_20options_5f_2c_20storageindex_5f_20_3e_20_3e_49',['SparseMatrixBase&lt; BlockSparseMatrix&lt; Scalar_, _BlockAtCompileTime, Options_, StorageIndex_ &gt; &gt;',['../../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrixt_20_3e_50',['SparseMatrixBase&lt; BlockSparseMatrixT &gt;',['../../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparseview_3c_20matrixtype_20_3e_20_3e_51',['SparseMatrixBase&lt; SparseView&lt; MatrixType &gt; &gt;',['../../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20triangularview_3c_20matrixtype_2c_20mode_20_3e_20_3e_52',['SparseMatrixBase&lt; TriangularView&lt; MatrixType, Mode &gt; &gt;',['../../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparseqr_53',['SparseQR',['../../classEigen_1_1SparseQR.html',1,'Eigen']]],
  ['sparseselfadjointview_54',['SparseSelfAdjointView',['../../classEigen_1_1SparseSelfAdjointView.html',1,'Eigen']]],
  ['sparsesolverbase_55',['SparseSolverBase',['../../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletelu_3c_20scalar_5f_20_3e_20_3e_56',['SparseSolverBase&lt; IncompleteLU&lt; Scalar_ &gt; &gt;',['../../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparselu_3c_20matrixtype_5f_2c_20orderingtype_5f_20_3e_20_3e_57',['SparseSolverBase&lt; SparseLU&lt; MatrixType_, OrderingType_ &gt; &gt;',['../../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparseqr_3c_20matrixtype_5f_2c_20orderingtype_5f_20_3e_20_3e_58',['SparseSolverBase&lt; SparseQR&lt; MatrixType_, OrderingType_ &gt; &gt;',['../../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20spqr_3c_20matrixtype_5f_20_3e_20_3e_59',['SparseSolverBase&lt; SPQR&lt; MatrixType_ &gt; &gt;',['../../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20umfpacklu_3c_20matrixtype_5f_20_3e_20_3e_60',['SparseSolverBase&lt; UmfPackLU&lt; MatrixType_ &gt; &gt;',['../../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsevector_61',['SparseVector',['../../classEigen_1_1SparseVector.html',1,'Eigen']]],
  ['sparseview_62',['SparseView',['../../classEigen_1_1SparseView.html',1,'Eigen']]],
  ['spline_63',['Spline',['../classEigen_1_1Spline.html',1,'Eigen']]],
  ['splinefitting_64',['SplineFitting',['../structEigen_1_1SplineFitting.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20scalar_5f_2c_20dim_5f_2c_20degree_5f_20_3e_2c_20_5fderivativeorder_20_3e_65',['SplineTraits&lt; Spline&lt; Scalar_, Dim_, Degree_ &gt;, _DerivativeOrder &gt;',['../structEigen_1_1SplineTraits_3_01Spline_3_01Scalar___00_01Dim___00_01Degree___01_4_00_01__DerivativeOrder_01_4.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20scalar_5f_2c_20dim_5f_2c_20degree_5f_20_3e_2c_20dynamic_20_3e_66',['SplineTraits&lt; Spline&lt; Scalar_, Dim_, Degree_ &gt;, Dynamic &gt;',['../structEigen_1_1SplineTraits_3_01Spline_3_01Scalar___00_01Dim___00_01Degree___01_4_00_01Dynamic_01_4.html',1,'Eigen']]],
  ['spqr_67',['SPQR',['../../classEigen_1_1SPQR.html',1,'Eigen']]],
  ['staticsgroup_68',['StaticSGroup',['../classEigen_1_1StaticSGroup.html',1,'Eigen']]],
  ['stdmaptraits_69',['StdMapTraits',['../structEigen_1_1StdMapTraits.html',1,'Eigen']]],
  ['stdunorderedmaptraits_70',['StdUnorderedMapTraits',['../structEigen_1_1StdUnorderedMapTraits.html',1,'Eigen']]],
  ['stride_71',['Stride',['../../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e_72',['Stride&lt; 0, Value &gt;',['../../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_20value_2c_200_20_3e_73',['Stride&lt; Value, 0 &gt;',['../../classEigen_1_1Stride.html',1,'Eigen']]],
  ['superilu_74',['SuperILU',['../../classEigen_1_1SuperILU.html',1,'Eigen']]],
  ['superlu_75',['SuperLU',['../../classEigen_1_1SuperLU.html',1,'Eigen']]],
  ['superlubase_76',['SuperLUBase',['../../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20matrixtype_5f_2c_20superilu_3c_20matrixtype_5f_20_3e_20_3e_77',['SuperLUBase&lt; MatrixType_, SuperILU&lt; MatrixType_ &gt; &gt;',['../../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20matrixtype_5f_2c_20superlu_3c_20matrixtype_5f_20_3e_20_3e_78',['SuperLUBase&lt; MatrixType_, SuperLU&lt; MatrixType_ &gt; &gt;',['../../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['svdbase_79',['SVDBase',['../../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20bdcsvd_3c_20matrixtype_5f_2c_20options_5f_20_3e_20_3e_80',['SVDBase&lt; BDCSVD&lt; MatrixType_, Options_ &gt; &gt;',['../../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20jacobisvd_3c_20matrixtype_5f_2c_20options_5f_20_3e_20_3e_81',['SVDBase&lt; JacobiSVD&lt; MatrixType_, Options_ &gt; &gt;',['../../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['symbolexpr_82',['SymbolExpr',['../../classEigen_1_1symbolic_1_1SymbolExpr.html',1,'Eigen::symbolic']]],
  ['symbolvalue_83',['SymbolValue',['../../classEigen_1_1symbolic_1_1SymbolValue.html',1,'Eigen::symbolic']]]
];
