var searchData=
[
  ['skyline_20module_0',['Skyline module',['../group__Skyline__Module.html',1,'']]],
  ['slicing_20and_20indexing_1',['Slicing and Indexing',['../../group__TutorialSlicingIndexing.html',1,'']]],
  ['solving_20linear_20least_20squares_20systems_2',['Solving linear least squares systems',['../../group__LeastSquares.html',1,'']]],
  ['solving_20sparse_20linear_20systems_3',['Solving Sparse Linear Systems',['../../group__TopicSparseSystems.html',1,'']]],
  ['space_20transformations_4',['Space transformations',['../../group__TutorialGeometry.html',1,'']]],
  ['sparse_20linear_20algebra_5',['Sparse linear algebra',['../../group__Sparse__chapter.html',1,'']]],
  ['sparse_20matrix_20manipulations_6',['Sparse matrix manipulations',['../../group__TutorialSparse.html',1,'']]],
  ['sparse_20meta_2dmodule_7',['Sparse meta-module',['../../group__Sparse__Module.html',1,'']]],
  ['sparsecholesky_20module_8',['SparseCholesky module',['../../group__SparseCholesky__Module.html',1,'']]],
  ['sparsecore_20module_9',['SparseCore module',['../../group__SparseCore__Module.html',1,'']]],
  ['sparseextra_20module_10',['SparseExtra module',['../group__SparseExtra__Module.html',1,'']]],
  ['sparselu_20module_11',['SparseLU module',['../../group__SparseLU__Module.html',1,'']]],
  ['sparseqr_20module_12',['SparseQR module',['../../group__SparseQR__Module.html',1,'']]],
  ['special_20math_20functions_20module_13',['Special math functions module',['../group__SpecialFunctions__Module.html',1,'']]],
  ['spline_20and_20spline_20fitting_20module_14',['Spline and spline fitting module',['../group__Splines__Module.html',1,'']]],
  ['stl_20iterators_20and_20algorithms_15',['STL iterators and algorithms',['../../group__TutorialSTL.html',1,'']]],
  ['storage_20orders_16',['Storage orders',['../../group__TopicStorageOrders.html',1,'']]],
  ['structures_20having_20eigen_20members_17',['Structures Having Eigen Members',['../../group__TopicStructHavingEigenMembers.html',1,'']]],
  ['suitesparseqr_20module_18',['SuiteSparseQR module',['../../group__SPQRSupport__Module.html',1,'']]],
  ['superlusupport_20module_19',['SuperLUSupport module',['../../group__SuperLUSupport__Module.html',1,'']]],
  ['support_20modules_20',['Support modules',['../../group__Support__modules.html',1,'']]],
  ['svd_20module_21',['SVD module',['../../group__SVD__Module.html',1,'']]]
];
